project_id = "cveapedneuhgbxqydpjc"

[functions.generate-protocol]
verify_jwt = true

[functions.nocobase-sync]
verify_jwt = true

[functions.nocobase-abandoned-cart]
verify_jwt = false

[functions.community-join]
verify_jwt = false

[functions.payfast-create-payment]
verify_jwt = true

[functions.payfast-itn]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
