CREATE TABLE "public"."psa_pets_checkout_consents" (
  "id"                             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id"                       uuid                     NOT NULL,
  "user_id"                        uuid                     NOT NULL,
  "policy_version"                 text                     NOT NULL,
  "report_scope_version"           text                     NOT NULL,
  "age_confirmed"                  boolean                  NOT NULL,
  "nutritional_scope_acknowledged" boolean                  NOT NULL,
  "label_use_acknowledged"         boolean                  NOT NULL,
  "report_scope_acknowledged"      boolean                  NOT NULL,
  "marketing_consent"              boolean                  NOT NULL DEFAULT false,
  "client_accepted_at"             timestamp with time zone NOT NULL,
  "accepted_at"                    timestamp with time zone NOT NULL DEFAULT now(),
  "statements"                     jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "source"                         text                     NOT NULL DEFAULT 'pets_checkout'::text,
  CONSTRAINT "psa_pets_checkout_consents_age_confirmed_check" CHECK (age_confirmed),
  CONSTRAINT "psa_pets_checkout_consents_label_use_acknowledged_check" CHECK (label_use_acknowledged),
  CONSTRAINT "psa_pets_checkout_consents_nutritional_scope_acknowledged_check" CHECK (nutritional_scope_acknowledged),
  CONSTRAINT "psa_pets_checkout_consents_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE RESTRICT,
  CONSTRAINT "psa_pets_checkout_consents_order_id_key" UNIQUE (order_id),
  CONSTRAINT "psa_pets_checkout_consents_pkey" PRIMARY KEY (id),
  CONSTRAINT "psa_pets_checkout_consents_policy_version_check" CHECK (((char_length(policy_version) >= 1) AND (char_length(policy_version) <= 80))),
  CONSTRAINT "psa_pets_checkout_consents_report_scope_acknowledged_check" CHECK (report_scope_acknowledged),
  CONSTRAINT "psa_pets_checkout_consents_report_scope_version_check" CHECK (((char_length(report_scope_version) >= 1) AND (char_length(report_scope_version) <= 80))),
  CONSTRAINT "psa_pets_checkout_consents_source_check" CHECK (((char_length(source) >= 1) AND (char_length(source) <= 80))),
  CONSTRAINT "psa_pets_checkout_consents_statements_check" CHECK ((jsonb_typeof(statements) = 'object'::text)),
  CONSTRAINT "psa_pets_checkout_consents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE RESTRICT
);

ALTER TABLE "public"."psa_pets_checkout_consents"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX psa_pets_checkout_consents_user_accepted_idx ON public.psa_pets_checkout_consents USING btree (user_id, accepted_at DESC);

CREATE POLICY "psa_pets_checkout_consents_owner_or_admin_select" ON "public"."psa_pets_checkout_consents"
  FOR SELECT
  TO "authenticated"
  USING (((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT public.has_role(( SELECT auth.uid() AS uid), 'admin'::public.app_role) AS has_role)));

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."psa_pets_checkout_consents" TO "postgres", "service_role";

COMMENT ON TABLE "public"."psa_pets_checkout_consents" IS 'Immutable, versioned Peptides4Pets checkout acknowledgement receipts.';

REVOKE ALL ON TABLE "public"."psa_pets_checkout_consents" FROM "authenticated";

GRANT SELECT ON TABLE "public"."psa_pets_checkout_consents" TO "authenticated";
