CREATE TABLE "tracker"."crm_activities" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lead_id"       uuid                     NOT NULL,
  "activity_type" text                     NOT NULL,
  "activity_data" jsonb,
  "page_url"      text,
  "session_id"    text,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "crm_activities_activity_type_check"
    CHECK
    ((activity_type = ANY (ARRAY['page_view'::text, 'qa_signup'::text, 'course_start'::text, 'calculator_use'::text, 'premium_click'::text, 'pricing_view'::text,
    'peptide_search'::text, 'email_open'::text, 'consultation_booked'::text, 'store_click'::text, 'account_created'::text]))),
  CONSTRAINT "crm_activities_pkey" PRIMARY KEY (id),
  CONSTRAINT "crm_activities_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES tracker.crm_leads(id) ON DELETE CASCADE
);

ALTER TABLE "tracker"."crm_activities"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX crm_activities_lead_created_idx ON tracker.crm_activities USING btree (lead_id, created_at DESC);

CREATE INDEX crm_activities_session_created_idx ON tracker.crm_activities USING btree (session_id, created_at DESC)
  WHERE (session_id IS NOT NULL);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "tracker"."crm_activities" TO "postgres", "service_role";
