import type { BlogPost } from "../types";

export const post: BlogPost = {
  slug: "south-africa-glp-1-recall-2026",
  title: "South Africa's 2026 GLP-1 Recall: How to Verify Semaglutide and Tirzepatide",
  metaTitle: "South Africa GLP-1 Recall 2026: Verification Guide",
  metaDescription:
    "What SAHPRA's 2026 iDEXIS semaglutide and tirzepatide recall means, how to verify a medicine, and where South Africans can report concerns.",
  keyword: "semaglutide tirzepatide recall South Africa",
  publishedAt: "2026-09-02",
  updatedAt: "2026-09-02",
  readingMinutes: 9,
  category: "South African Regulation",
  hero: {
    eyebrow: "South African regulatory analysis",
    summary:
      "SAHPRA, the SAPC and the HPCSA have warned against continued use or dispensing of recalled iDEXIS semaglutide and tirzepatide products. This source-led guide explains the recall, the limits of compounding and Section 21 access, and the checks that matter before a medicine reaches a patient.",
  },
  body: [
    {
      type: "callout",
      title: "The short version",
      text: "The recall names iDEXIS Semaglutide, iDEXIS Tirzepatide and iDEXIS Semaglutide/Tirzepatide. SAHPRA classified it as Class I, Type A and says the recalled products pose a serious patient-safety risk. Do not use a named recalled product. Keep it separate, contact the dispensing pharmacy and prescriber, and use SAHPRA's recall notice and Med Safety reporting channels for next steps.<sup>1,2</sup>",
    },
    { type: "h2", text: "What South African regulators reported" },
    {
      type: "p",
      text: "On 11 May 2026, the South African Health Products Regulatory Authority (SAHPRA) and South African Pharmacy Council (SAPC) inspected iDexis (Pty) Ltd, trading as Sentra Pharmacy, in Silverton, Pretoria. Their 23 May statement said injectable products were seized and alleged that semaglutide, tirzepatide and combination products were being produced and supplied beyond the legal limits of patient-specific compounding.<sup>3</sup>",
    },
    {
      type: "p",
      text: "The regulators reported illegal importation of active pharmaceutical ingredients, no analytical testing to confirm identity, potency and purity, inadequate conditions for sterile preparation, and no pharmacovigilance system. They also referred to adverse-event reports, including hospitalisations. These are regulator-reported inspection findings, not findings independently generated by Peptide South Africa.<sup>3</sup>",
    },
    {
      type: "p",
      text: "SAHPRA published the product recall on 22 May. On 8 July, SAHPRA, SAPC and the Health Professions Council of South Africa (HPCSA) jointly warned the public, pharmacies and dispensing practitioners against continued use, prescription or dispensing of the recalled iDEXIS products. The joint statement describes the action as a <strong>Class I, Type A recall</strong> and says the products pose a serious safety risk.<sup>1,2</sup>",
    },
    { type: "h2", text: "Exactly which names are covered?" },
    {
      type: "p",
      text: "The official warning names three product lines: <strong>iDEXIS Semaglutide</strong>, <strong>iDEXIS Tirzepatide</strong>, and <strong>iDEXIS Semaglutide/Tirzepatide</strong>. It does not say that every registered medicine containing semaglutide or tirzepatide is recalled. Recall status attaches to the named products and the details in SAHPRA's recall record, not to a molecule in the abstract.<sup>1,2</sup>",
    },
    {
      type: "callout",
      title: "Do not identify a product by molecule name alone",
      text: "Match the brand or product name, supplier, batch and expiry details against the current SAHPRA notice. Packaging photographs, social-media assurances or a seller's description are not substitutes for the regulator's record.",
    },
    { type: "h2", text: "Registered medicine, compounding and Section 21 are different routes" },
    {
      type: "table",
      caption: "Regulatory routes should not be treated as interchangeable.",
      headers: ["Route", "What it establishes", "What it does not establish"],
      rows: [
        [
          "SAHPRA-registered medicine",
          "A specific product has been evaluated and registered for stated indications, presentations and conditions.",
          "Registration of one product does not automatically approve every product containing the same active ingredient.",
        ],
        [
          "Patient-specific compounding",
          "A pharmacist may prepare a medicine within the applicable legal framework for an identified patient's valid prescription.",
          "It is not a route for large-scale manufacture, general advertising or broad commercial distribution of unregistered medicine.",
        ],
        [
          "Section 21 access",
          "SAHPRA may authorise access to a specified unregistered medicine when the statutory and guideline requirements are met.",
          "It is not blanket registration, open retail permission or proof that any similarly labelled online product is authorised.",
        ],
        [
          "Research-labelled material",
          "The label states the seller's claimed purpose.",
          "The words 'research use only' do not establish SAHPRA registration, Section 21 authorisation, patient suitability, sterility or clinical efficacy.",
        ],
      ],
    },
    {
      type: "p",
      text: "SAHPRA's current Section 21 guideline describes a controlled pathway for access to unregistered medicines for human use. Authorisation is application-specific and subject to regulatory conditions; it should not be inferred from a seller's website, a prescription alone or the presence of an analytical certificate.<sup>4</sup>",
    },
    { type: "h2", text: "What a certificate of analysis can and cannot prove" },
    {
      type: "p",
      text: "A genuine, batch-linked laboratory report can be useful evidence about the tests actually performed on the submitted sample. Depending on the method, it may support an identity or purity claim. It does <strong>not</strong>, by itself, prove that the finished product is SAHPRA-registered, sterile, stable for the claimed shelf life, manufactured under an authorised quality system, clinically effective, correctly transported or suitable for a particular patient.",
    },
    {
      type: "ul",
      items: [
        "Confirm that the batch number on the report exactly matches the batch on the package.",
        "Check the laboratory name, report identifier, test date, sample description and methods used.",
        "Distinguish identity or purity testing from sterility, endotoxin, potency, stability and finished-product release testing.",
        "Verify the report with the named laboratory when a verification link or contact channel is available.",
        "Treat the report as one piece of evidence—not as regulatory approval or a treatment recommendation.",
      ],
    },
    { type: "h2", text: "A practical verification checklist for South Africans" },
    {
      type: "ol",
      items: [
        "Search the exact product name in SAHPRA's Registered Health Products resources or Medicines Online Directory; do not rely only on the active ingredient name.<sup>5</sup>",
        "Check SAHPRA's current product-recall page and open the underlying notice for the exact name and available product details.<sup>6</sup>",
        "Verify that the prescriber is registered with the HPCSA and that the supplying pharmacy or pharmacist appears in the SAPC register.<sup>7</sup>",
        "Compare the package name, strength, dosage form, batch, expiry and supplier with the prescription and official product information. Ask the pharmacist to resolve any mismatch.",
        "Be cautious when a seller substitutes a 'research' label, an analytical report or a low price for a verifiable regulatory and supply-chain record.",
        "Do not continue using a product named in the recall. Contact the dispensing pharmacy and prescriber for product-specific instructions; seek urgent medical help for severe or rapidly worsening symptoms.",
      ],
    },
    { type: "h2", text: "How the WHO's July 2026 statement fits" },
    {
      type: "p",
      text: "On 30 July 2026, World Health Organization safety advisory committees said GLP-1 receptor agonists have a positive benefit–risk balance when used for approved indications under qualified clinical supervision. The same statement warned that self-medication, unverified online sources and use without safety follow-up create preventable risk because identity, quality, purity and strength may not be assured.<sup>8</sup>",
    },
    {
      type: "p",
      text: "That distinction matters. Evidence supporting an approved medicine in a defined patient population does not validate an unregistered copy, a combination formulation, an unidentified powder or a self-directed protocol. Product identity, legal route, indication, manufacturing controls and clinical supervision are separate questions.",
    },
    { type: "h2", text: "If you have an affected or suspicious product" },
    {
      type: "ul",
      items: [
        "Do not use a product identified in the recall, and do not pass it to another person.",
        "Keep the container, packaging, receipt and any correspondence; they may be needed to identify the batch and supply route.",
        "Contact the dispensing pharmacy and prescribing clinician for instructions on return, replacement and clinical follow-up.",
        "Report a suspected adverse reaction through SAHPRA's Med Safety system. Both members of the public and healthcare practitioners can report.<sup>9</sup>",
        "Report suspected unlawful sale or distribution through SAHPRA's official reporting channels.",
      ],
    },
    {
      type: "callout",
      title: "Evidence boundary",
      text: "This article is a dated regulatory explainer, not legal advice, a diagnosis or an individual treatment plan. It contains no dosing guidance. Recall notices and registration records can change; use the linked regulator pages as the current source of truth.",
    },
  ],
  citations: [
    {
      id: "1",
      label: "SAHPRA, SAPC and HPCSA. Health regulators warn against the use or dispensing of recalled Semaglutide and Tirzepatide. 8 July 2026.",
      url: "https://www.sahpra.org.za/health-regulators-warn-against-the-use-or-dispensing-of-recalled-semaglutide-and-tirzepatide/",
    },
    {
      id: "2",
      label: "SAHPRA. iDEXIS Semaglutide, iDEXIS Tirzepatide, iDEXIS Semaglutide/Tirzepatide recall record. Updated 22 May 2026.",
      url: "https://www.sahpra.org.za/document/idexis-semaglutide-idexis-tirzepatide-idexissemaglutide-tirzepatide/",
    },
    {
      id: "3",
      label: "SAHPRA and SAPC. Crackdown on unlawful manufacturing of unregistered GLP-1/GIP medicines. 23 May 2026.",
      url: "https://www.sahpra.org.za/sahpra-and-the-sapc-crack-down-on-unlawful-manufacturing-of-unregistered-glp-1-medicines/",
    },
    {
      id: "4",
      label: "SAHPRA. Guideline for Section 21 Access to Unregistered Medicines, Version 6. Updated 30 October 2025.",
      url: "https://www.sahpra.org.za/document/guideline-for-section-21-access-to-unregistered-medicines/",
    },
    {
      id: "5",
      label: "SAHPRA. Medicines Online Directory for registered OTC and prescription medicines.",
      url: "https://medsinfo.sahpra.org.za/",
    },
    {
      id: "6",
      label: "SAHPRA. Product recalls database.",
      url: "https://www.sahpra.org.za/product-recalls/",
    },
    {
      id: "7",
      label: "South African Pharmacy Council. Public register and registered-organisation search.",
      url: "https://www.sapc.za.org/",
    },
    {
      id: "8",
      label: "World Health Organization. Statement on the safe and appropriate use of GLP-1 receptor agonists. 30 July 2026.",
      url: "https://www.who.int/news/item/30-07-2026-statement-from-the-joint-meeting-of-the-advisory-committee-on-safety-of-medicinal-products-(acsomp)-and-the-global-advisory-committee-on-vaccine-safety-(gacvs)-on-the-safe-and-appropriate-use-of-glp-1-receptor-agonists",
    },
    {
      id: "9",
      label: "SAHPRA. Med Safety adverse-drug-reaction reporting service.",
      url: "https://medsafety.sahpra.org.za/",
    },
  ],
  faqs: [
    {
      q: "Which semaglutide and tirzepatide products were recalled in South Africa in 2026?",
      a: "The joint SAHPRA, SAPC and HPCSA warning names iDEXIS Semaglutide, iDEXIS Tirzepatide and iDEXIS Semaglutide/Tirzepatide. Check SAHPRA's recall record for the current product details; the warning does not state that every product containing either molecule is recalled.",
    },
    {
      q: "What does Class I, Type A recall mean for a patient?",
      a: "SAHPRA's 8 July statement says the recalled iDEXIS products pose a serious patient-safety risk and warns against continued use, prescription or dispensing. A person holding one should not use it and should contact the dispensing pharmacy and prescriber for product-specific instructions.",
    },
    {
      q: "Does a certificate of analysis prove that a peptide medicine is approved?",
      a: "No. A batch-linked report may support only the laboratory tests it records. It does not establish SAHPRA registration, Section 21 authorisation, sterile manufacture, stability, clinical efficacy or suitability for an individual patient.",
    },
    {
      q: "Is a compounded GLP-1 medicine the same as a registered medicine?",
      a: "No. Patient-specific compounding and product registration are different regulatory routes. SAHPRA and SAPC state that compounding cannot be used as a mechanism for large-scale manufacture, advertising or broad distribution of unregistered medicines.",
    },
    {
      q: "Where can a South African report a suspected side effect?",
      a: "SAHPRA's Med Safety service accepts suspected adverse-drug-reaction reports from members of the public and healthcare practitioners. For urgent symptoms, seek medical care first.",
    },
  ],
  cta: "club",
  related: [
    "how-to-spot-a-legit-peptide-supplier",
    "tirzepatide-vs-semaglutide-comparison",
    "peptide-bloodwork-markers-sa",
  ],
};
