-- First-party CRM for Peptide South Africa. PII remains server-only and is
-- accessed exclusively through authenticated Edge Functions.

create table if not exists tracker.crm_leads (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  first_name text,
  last_name text,
  phone text,
  source text not null,
  plan_interest text not null default 'undecided'
    check (plan_interest in ('free', 'premium', 'undecided')),
  lead_status text not null default 'new'
    check (lead_status in ('new', 'nurturing', 'qualified', 'converted')),
  lead_score smallint not null default 0 check (lead_score between 0 and 100),
  last_activity_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_leads_email_normalized check (email = lower(trim(email))),
  constraint crm_leads_email_unique unique (email)
);

create table if not exists tracker.crm_activities (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references tracker.crm_leads(id) on delete cascade,
  activity_type text not null check (activity_type in (
    'page_view', 'qa_signup', 'course_start', 'calculator_use',
    'premium_click', 'pricing_view', 'peptide_search', 'email_open',
    'consultation_booked'
  )),
  activity_data jsonb,
  page_url text,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists crm_leads_last_activity_idx
  on tracker.crm_leads (last_activity_at desc);
create index if not exists crm_leads_status_score_idx
  on tracker.crm_leads (lead_status, lead_score desc);
create index if not exists crm_activities_lead_created_idx
  on tracker.crm_activities (lead_id, created_at desc);
create index if not exists crm_activities_session_created_idx
  on tracker.crm_activities (session_id, created_at desc)
  where session_id is not null;

alter table tracker.crm_leads enable row level security;
alter table tracker.crm_activities enable row level security;

-- Defence in depth: the Data API roles cannot reach CRM PII at all. Edge
-- Functions use the service role after their own request/admin validation.
revoke all on tracker.crm_leads from anon, authenticated;
revoke all on tracker.crm_activities from anon, authenticated;
grant all on tracker.crm_leads to service_role;
grant all on tracker.crm_activities to service_role;
grant usage, select on sequence tracker.crm_activities_id_seq to service_role;

create or replace function tracker.capture_crm_activity(
  p_email text,
  p_first_name text,
  p_last_name text,
  p_phone text,
  p_source text,
  p_plan_interest text,
  p_activity_type text,
  p_score_delta integer,
  p_activity_data jsonb,
  p_page_url text,
  p_session_id text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_lead tracker.crm_leads%rowtype;
  v_activity_id bigint;
  v_status text;
begin
  insert into tracker.crm_leads (
    email, first_name, last_name, phone, source, plan_interest,
    lead_status, lead_score, last_activity_at
  ) values (
    lower(trim(p_email)), nullif(trim(p_first_name), ''),
    nullif(trim(p_last_name), ''), nullif(trim(p_phone), ''), trim(p_source),
    p_plan_interest,
    case
      when p_activity_type = 'premium_click' or p_score_delta >= 60 then 'qualified'
      when p_score_delta >= 30 then 'nurturing'
      else 'new'
    end,
    least(100, greatest(0, p_score_delta)), now()
  )
  on conflict (email) do update set
    first_name = coalesce(tracker.crm_leads.first_name, excluded.first_name),
    last_name = coalesce(tracker.crm_leads.last_name, excluded.last_name),
    phone = coalesce(tracker.crm_leads.phone, excluded.phone),
    source = coalesce(nullif(excluded.source, ''), tracker.crm_leads.source),
    plan_interest = case
      when excluded.plan_interest = 'premium' then 'premium'
      when excluded.plan_interest = 'free' and tracker.crm_leads.plan_interest <> 'premium' then 'free'
      else tracker.crm_leads.plan_interest
    end,
    lead_score = least(100, tracker.crm_leads.lead_score + greatest(0, p_score_delta)),
    last_activity_at = now(),
    updated_at = now()
  returning * into v_lead;

  v_status := case
    when v_lead.lead_status = 'converted' then 'converted'
    when p_activity_type = 'premium_click' or v_lead.lead_score >= 60 then 'qualified'
    when v_lead.lead_score >= 30 then 'nurturing'
    else 'new'
  end;

  if v_status <> v_lead.lead_status then
    update tracker.crm_leads set lead_status = v_status, updated_at = now()
      where id = v_lead.id;
    v_lead.lead_status := v_status;
  end if;

  insert into tracker.crm_activities (
    lead_id, activity_type, activity_data, page_url, session_id
  ) values (
    v_lead.id, p_activity_type, p_activity_data, p_page_url, p_session_id
  ) returning id into v_activity_id;

  return jsonb_build_object(
    'lead_id', v_lead.id,
    'activity_id', v_activity_id,
    'lead_score', v_lead.lead_score,
    'lead_status', v_lead.lead_status
  );
end;
$$;

revoke execute on function tracker.capture_crm_activity(
  text, text, text, text, text, text, text, integer, jsonb, text, text
) from public, anon, authenticated;
grant execute on function tracker.capture_crm_activity(
  text, text, text, text, text, text, text, integer, jsonb, text, text
) to service_role;

notify pgrst, 'reload schema';
;
